### ISSUE TITLE
Sort tag list

### ISSUE THREAD

**Issue by phistep** [wchaering/tagsort#4]
I would love it, if there was an option to sort the tags list (`itemTagsView`) alphabetically (or maybe make it the default?).

Something nice to have would be a way specify pinned tags (I use a hidden dummy element that carries all tags that should be at the start of the list, and put it in front of all real items). But I don't really imagine a practical user interface for that. This one is really just an idea, whereas the sorting seems very important to me.

**Comment by beerendlauwers** [comment]
See this (rejected) pull request: https://github.com/wchaering/tagsort/pull/1

**Comment by beerendlauwers** [comment]
I provided a new pull request: https://github.com/wchaering/tagsort/pull/5
